from pydantic import BaseModel, Field
from typing import Optional


class STSRoomCreate(BaseModel):
    """
    Schema for creating an STS agent room.
    Room name is auto-generated by the backend as: MF-{CustomerName}-{uuid_short}.
    """
    persona: str = Field(
        "default",
        description="Persona preset key (default, angry, rude, cool, skeptical, confused, demanding, wtw)"
    )
    language: str = Field("en", description="Language code (en, ml, hi, ta, bn, etc.)")
    custom_instructions: Optional[str] = Field(
        None, description="Optional custom prompt override for the STS agent"
    )
    # Optional persona profile overrides
    customer_name: Optional[str] = Field(
        None, description="Customer name; used as the room name prefix if provided"
    )
    age: Optional[int] = Field(None, description="Customer age override")
    occupation: Optional[str] = Field(None, description="Customer occupation override")
    location: Optional[str] = Field(None, description="Customer location override")
    monthly_income: Optional[int] = Field(None, description="Monthly income override")
    current_savings: Optional[int] = Field(None, description="Current savings override")
    risk_appetite: Optional[str] = Field(None, description="Risk appetite override (Low, Moderate, High)")
    empty_timeout: int = Field(300, description="Room auto-close timeout in seconds when empty")
    max_participants: int = Field(5, description="Maximum participants allowed in the room")


class STSTokenRequest(BaseModel):
    """
    Schema for generating a join token for an existing STS room.
    """
    identity: str = Field(..., description="Unique participant identity")
    username: Optional[str] = Field(None, description="Optional display name")


class STSRoomResponse(BaseModel):
    """
    Schema for the response after STS room creation.
    Includes the auto-generated room name, LiveKit connection details, and a pre-generated join token.
    """
    name: str = Field(..., description="Auto-generated room name: MF-{CustomerName}-{uuid_short}")
    sid: str = Field(..., description="LiveKit room SID")
    empty_timeout: int
    max_participants: int
    num_participants: int
    metadata: Optional[str] = Field(None, description="JSON persona config stored as room metadata")
    livekit_url: str = Field(..., description="STS LiveKit WebSocket URL for client connection")
    token: str = Field(..., description="Pre-generated join token for the human participant")
    identity: str = Field(..., description="Identity used for the generated token")
